#!/bin/bash

NETLIST=${1:-netlist.v}
OUTPUT=${2:-custom_cells.v}

echo "Scanning $NETLIST for sky130 cells..."

# Extract unique cell names from the given netlist
CELLS=$(grep -oP 'sky130_fd_sc_hd__\w+' "$NETLIST" | sort -u)

# Also scan chained netlist if it exists
CHAINED="${NETLIST}.chained.v"
if [ -f "$CHAINED" ]; then
  echo "Also scanning $CHAINED..."
  CELLS=$(echo "$CELLS"; grep -oP 'sky130_fd_sc_hd__\w+' "$CHAINED")
  CELLS=$(echo "$CELLS" | sort -u)
fi

# Also scan jtag netlist if it exists
JTAG="${NETLIST%.chained.v}.jtag.v"
if [ -f "$JTAG" ]; then
  echo "Also scanning $JTAG..."
  CELLS=$(echo "$CELLS"; grep -oP 'sky130_fd_sc_hd__\w+' "$JTAG")
  CELLS=$(echo "$CELLS" | sort -u)
fi

# Always include cells that fault chain/tap inserts during resynthesis
ALWAYS_NEEDED="
sky130_fd_sc_hd__and2_0
sky130_fd_sc_hd__and3_1
sky130_fd_sc_hd__a211o_1
sky130_fd_sc_hd__a2111oi_0
sky130_fd_sc_hd__dfrtp_1
sky130_fd_sc_hd__dfstp_1
sky130_fd_sc_hd__dfstp_2
sky130_fd_sc_hd__dfxtp_1
sky130_fd_sc_hd__lpflow_inputiso1p_1
sky130_fd_sc_hd__mux2_1
sky130_fd_sc_hd__mux2i_1
sky130_fd_sc_hd__nand2_1
sky130_fd_sc_hd__nand2b_1
sky130_fd_sc_hd__nor2_1
sky130_fd_sc_hd__nor3_1
sky130_fd_sc_hd__nor4_1
sky130_fd_sc_hd__nor4b_1
sky130_fd_sc_hd__o21ai_0
sky130_fd_sc_hd__o22ai_1
sky130_fd_sc_hd__o31ai_1
sky130_fd_sc_hd__or4_1
"

CELLS=$(echo "$CELLS"; echo "$ALWAYS_NEEDED")
CELLS=$(echo "$CELLS" | tr ' ' '\n' | sed '/^$/d' | sort -u)

echo "Found cells:"
echo "$CELLS"
echo ""

# Start output file
cat > "$OUTPUT" << 'HEADER'
// Auto-generated behavioral cell models
// Generated by build_cell_model.sh
HEADER

for CELL in $CELLS; do
  echo "Building model for: $CELL"

  case $CELL in

    # ----------------------------------------------------------------
    # Inverters / Buffers
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__clkinv_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, VPWR, VGND, VPB, VNB);
  output Y; input A, VPWR, VGND, VPB, VNB;
  assign Y = ~A;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__inv_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, VPWR, VGND, VPB, VNB);
  output Y; input A, VPWR, VGND, VPB, VNB;
  assign Y = ~A;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__buf_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, VPWR, VGND, VPB, VNB);
  output X; input A, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # AND gates
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__and2_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A & B;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__and3_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A & B & C;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__and4_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, D, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign X = A & B & C & D;
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # OR gates
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__or2_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A | B;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__or3b_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C_N, VPWR, VGND, VPB, VNB);
  output X; input A, B, C_N, VPWR, VGND, VPB, VNB;
  assign X = A | B | (~C_N);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__or3_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A | B | C;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__or4b_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, D_N, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D_N, VPWR, VGND, VPB, VNB;
  assign X = A | B | C | (~D_N);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__or4_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, D, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign X = A | B | C | D;
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # XOR / XNOR
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__xor2_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A ^ B;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__xor3_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A ^ B ^ C;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__xnor2_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A ^ B);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__xnor3_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = ~(A ^ B ^ C);
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # NAND gates
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__nand2b_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A_N, B, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & B);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nand2_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nand3b_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A_N, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & B & C);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nand3_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B & C);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nand4_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B & C & D);
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # NOR gates
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__nor2b_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | (~B_N));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nor2_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nor3b_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, C_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | (~C_N));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nor3_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nor4b_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, C, D_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C | (~D_N));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__nor4_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C | D);
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # Majority
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__maj3_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = (A & B) | (B & C) | (A & C);
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # MUX
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__mux2i_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A0, A1, S, VPWR, VGND, VPB, VNB);
  output Y; input A0, A1, S, VPWR, VGND, VPB, VNB;
  assign Y = ~(S ? A1 : A0);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__mux2_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A0, A1, S, VPWR, VGND, VPB, VNB);
  output X; input A0, A1, S, VPWR, VGND, VPB, VNB;
  assign X = S ? A1 : A0;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__mux4_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB);
  output X; input A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB;
  assign X = S1 ? (S0 ? A3 : A2) : (S0 ? A1 : A0);
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # Flip-flops
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__dfxtp_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Q, CLK, D, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK) Q <= D;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__dfrtp_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Q, CLK, D, RESET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, RESET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge RESET_B)
    if (!RESET_B) Q <= 0; else Q <= D;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__dfstp_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Q, CLK, D, SET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, SET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge SET_B)
    if (!SET_B) Q <= 1; else Q <= D;
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # Low-power / isolation cells
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__lpflow_isobufsrc_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, SLEEP, VPWR, VGND, VPB, VNB);
  output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__lpflow_inputiso1p_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A, SLEEP, VPWR, VGND, VPB, VNB);
  output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
  assign X = A & SLEEP;
endmodule
ENDCELL
      ;;

    # ----------------------------------------------------------------
    # AOI / OAI complex gates
    # ----------------------------------------------------------------
    sky130_fd_sc_hd__a2111oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1 | C1 | D1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a211oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1 | C1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a211o_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | B1 | C1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a221oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (B1 & B2) | C1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a221o_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (B1 & B2) | C1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a22oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (B1 & B2));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a22o_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (B1 & B2);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a21boi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (~B1_N));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a21bo_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (~B1_N);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a21oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a21o_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | B1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a311oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | B1 | C1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a311o_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3) | B1 | C1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a32oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | (B1 & B2));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a31oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | B1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a31o_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3) | B1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__a41oi_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3 & A4) | B1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o2111a_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2) & B1) | C1 | D1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o211ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & B1 & C1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o211a_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2) & B1) | C1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o221ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (B1 | B2) & C1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o22ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (B1 | B2));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o22a_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2) & (B1 | B2);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o21bai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (~B1_N));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o21ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & B1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o21a_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2) & B1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o311ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & B1 & C1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o311a_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2 | A3) & B1) | C1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o32ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & (B1 | B2));
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o31ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & B1);
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o31a_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (X, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2 | A3) & B1;
endmodule
ENDCELL
      ;;

    sky130_fd_sc_hd__o41ai_*)
      cat >> "$OUTPUT" << ENDCELL

module $CELL (Y, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3 | A4) & B1);
endmodule
ENDCELL
      ;;

    *)
      echo "  WARNING: No model for $CELL — skipping"
      ;;
  esac
done

echo ""
echo "Done! Written to $OUTPUT"
echo "Modules generated:"
grep "^module" "$OUTPUT"