// Auto-generated behavioral cell models
// Generated by build_cell_model.sh

module sky130_fd_sc_hd__a2111oi_0 (Y, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1 | C1 | D1);
endmodule

module sky130_fd_sc_hd__a211o_1 (X, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | B1 | C1;
endmodule

module sky130_fd_sc_hd__a211oi_1 (Y, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1 | C1);
endmodule

module sky130_fd_sc_hd__a21bo_1 (X, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (~B1_N);
endmodule

module sky130_fd_sc_hd__a21boi_0 (Y, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (~B1_N));
endmodule

module sky130_fd_sc_hd__a21o_1 (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | B1;
endmodule

module sky130_fd_sc_hd__a21oi_1 (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | B1);
endmodule

module sky130_fd_sc_hd__a221o_1 (X, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (B1 & B2) | C1;
endmodule

module sky130_fd_sc_hd__a221oi_1 (Y, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (B1 & B2) | C1);
endmodule

module sky130_fd_sc_hd__a22o_1 (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2) | (B1 & B2);
endmodule

module sky130_fd_sc_hd__a22oi_1 (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2) | (B1 & B2));
endmodule

module sky130_fd_sc_hd__a311o_1 (X, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3) | B1 | C1;
endmodule

module sky130_fd_sc_hd__a311oi_1 (Y, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | B1 | C1);
endmodule

module sky130_fd_sc_hd__a31o_1 (X, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 & A2 & A3) | B1;
endmodule

module sky130_fd_sc_hd__a31oi_1 (Y, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | B1);
endmodule

module sky130_fd_sc_hd__a32oi_1 (Y, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3) | (B1 & B2));
endmodule

module sky130_fd_sc_hd__a41oi_1 (Y, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 & A2 & A3 & A4) | B1);
endmodule

module sky130_fd_sc_hd__and2_0 (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A & B;
endmodule

module sky130_fd_sc_hd__and3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A & B & C;
endmodule

module sky130_fd_sc_hd__and4_1 (X, A, B, C, D, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign X = A & B & C & D;
endmodule

module sky130_fd_sc_hd__clkinv_1 (Y, A, VPWR, VGND, VPB, VNB);
  output Y; input A, VPWR, VGND, VPB, VNB;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__dfrtp_1 (Q, CLK, D, RESET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, RESET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge RESET_B)
    if (!RESET_B) Q <= 0; else Q <= D;
endmodule

module sky130_fd_sc_hd__dfstp_1 (Q, CLK, D, SET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, SET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge SET_B)
    if (!SET_B) Q <= 1; else Q <= D;
endmodule

module sky130_fd_sc_hd__dfstp_2 (Q, CLK, D, SET_B, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, SET_B, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK or negedge SET_B)
    if (!SET_B) Q <= 1; else Q <= D;
endmodule

module sky130_fd_sc_hd__dfxtp_1 (Q, CLK, D, VPWR, VGND, VPB, VNB);
  output Q; input CLK, D, VPWR, VGND, VPB, VNB;
  reg Q;
  always @(posedge CLK) Q <= D;
endmodule

module sky130_fd_sc_hd__lpflow_inputiso1p_1 (X, A, SLEEP, VPWR, VGND, VPB, VNB);
  output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
  assign X = A & SLEEP;
endmodule

module sky130_fd_sc_hd__lpflow_isobufsrc_1 (X, A, SLEEP, VPWR, VGND, VPB, VNB);
  output X; input A, SLEEP, VPWR, VGND, VPB, VNB;
  assign X = A;
endmodule

module sky130_fd_sc_hd__maj3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = (A & B) | (B & C) | (A & C);
endmodule

module sky130_fd_sc_hd__mux2_1 (X, A0, A1, S, VPWR, VGND, VPB, VNB);
  output X; input A0, A1, S, VPWR, VGND, VPB, VNB;
  assign X = S ? A1 : A0;
endmodule

module sky130_fd_sc_hd__mux2i_1 (Y, A0, A1, S, VPWR, VGND, VPB, VNB);
  output Y; input A0, A1, S, VPWR, VGND, VPB, VNB;
  assign Y = ~(S ? A1 : A0);
endmodule

module sky130_fd_sc_hd__mux4_2 (X, A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB);
  output X; input A0, A1, A2, A3, S0, S1, VPWR, VGND, VPB, VNB;
  assign X = S1 ? (S0 ? A3 : A2) : (S0 ? A1 : A0);
endmodule

module sky130_fd_sc_hd__nand2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B);
endmodule

module sky130_fd_sc_hd__nand2b_1 (Y, A_N, B, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & B);
endmodule

module sky130_fd_sc_hd__nand3_1 (Y, A, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B & C);
endmodule

module sky130_fd_sc_hd__nand3b_1 (Y, A_N, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A_N, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~((~A_N) & B & C);
endmodule

module sky130_fd_sc_hd__nand4_1 (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~(A & B & C & D);
endmodule

module sky130_fd_sc_hd__nor2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B);
endmodule

module sky130_fd_sc_hd__nor2b_1 (Y, A, B_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | (~B_N));
endmodule

module sky130_fd_sc_hd__nor3_1 (Y, A, B, C, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C);
endmodule

module sky130_fd_sc_hd__nor3b_1 (Y, A, B, C_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | (~C_N));
endmodule

module sky130_fd_sc_hd__nor4_1 (Y, A, B, C, D, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C | D);
endmodule

module sky130_fd_sc_hd__nor4b_1 (Y, A, B, C, D_N, VPWR, VGND, VPB, VNB);
  output Y; input A, B, C, D_N, VPWR, VGND, VPB, VNB;
  assign Y = ~(A | B | C | (~D_N));
endmodule

module sky130_fd_sc_hd__o2111a_1 (X, A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, D1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2) & B1) | C1 | D1;
endmodule

module sky130_fd_sc_hd__o211a_1 (X, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2) & B1) | C1;
endmodule

module sky130_fd_sc_hd__o211ai_1 (Y, A1, A2, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & B1 & C1);
endmodule

module sky130_fd_sc_hd__o21a_1 (X, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2) & B1;
endmodule

module sky130_fd_sc_hd__o21ai_0 (Y, A1, A2, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & B1);
endmodule

module sky130_fd_sc_hd__o21bai_1 (Y, A1, A2, B1_N, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1_N, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (~B1_N));
endmodule

module sky130_fd_sc_hd__o221ai_1 (Y, A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (B1 | B2) & C1);
endmodule

module sky130_fd_sc_hd__o22a_1 (X, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2) & (B1 | B2);
endmodule

module sky130_fd_sc_hd__o22ai_1 (Y, A1, A2, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2) & (B1 | B2));
endmodule

module sky130_fd_sc_hd__o311a_1 (X, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign X = ((A1 | A2 | A3) & B1) | C1;
endmodule

module sky130_fd_sc_hd__o311ai_0 (Y, A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, C1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & B1 & C1);
endmodule

module sky130_fd_sc_hd__o31a_1 (X, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output X; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign X = (A1 | A2 | A3) & B1;
endmodule

module sky130_fd_sc_hd__o31ai_1 (Y, A1, A2, A3, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & B1);
endmodule

module sky130_fd_sc_hd__o32ai_1 (Y, A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, B1, B2, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3) & (B1 | B2));
endmodule

module sky130_fd_sc_hd__o41ai_1 (Y, A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB);
  output Y; input A1, A2, A3, A4, B1, VPWR, VGND, VPB, VNB;
  assign Y = ~((A1 | A2 | A3 | A4) & B1);
endmodule

module sky130_fd_sc_hd__or3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A | B | C;
endmodule

module sky130_fd_sc_hd__or3b_1 (X, A, B, C_N, VPWR, VGND, VPB, VNB);
  output X; input A, B, C_N, VPWR, VGND, VPB, VNB;
  assign X = A | B | (~C_N);
endmodule

module sky130_fd_sc_hd__or4_1 (X, A, B, C, D, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D, VPWR, VGND, VPB, VNB;
  assign X = A | B | C | D;
endmodule

module sky130_fd_sc_hd__or4b_1 (X, A, B, C, D_N, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, D_N, VPWR, VGND, VPB, VNB;
  assign X = A | B | C | (~D_N);
endmodule

module sky130_fd_sc_hd__xnor2_1 (Y, A, B, VPWR, VGND, VPB, VNB);
  output Y; input A, B, VPWR, VGND, VPB, VNB;
  assign Y = ~(A ^ B);
endmodule

module sky130_fd_sc_hd__xnor3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = ~(A ^ B ^ C);
endmodule

module sky130_fd_sc_hd__xor2_1 (X, A, B, VPWR, VGND, VPB, VNB);
  output X; input A, B, VPWR, VGND, VPB, VNB;
  assign X = A ^ B;
endmodule

module sky130_fd_sc_hd__xor3_1 (X, A, B, C, VPWR, VGND, VPB, VNB);
  output X; input A, B, C, VPWR, VGND, VPB, VNB;
  assign X = A ^ B ^ C;
endmodule
