/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-16 11:25:07
*/
`include "custom_cells.v"
`include "netlist.v.chained.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \clk ;
    wire[0:0] \zero_flag ;
    wire[0:0] \sout ;
    reg[0:0] \sin ;
    reg[31:0] \b ;
    reg[0:0] \test ;
    wire[31:0] \result ;
    reg[0:0] \tck ;
    reg[3:0] \select ;
    reg[31:0] \a ;
    reg[0:0] \rst_n ;
    reg[0:0] \shift ;

        always #(`CLOCK_PERIOD / 2) clk = ~clk; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    alu uut(
        .\clk ( \clk ) , .\zero_flag ( \zero_flag ) , .\sout ( \sout ) , .\sin ( \sin ) , .\b ( \b ) , .\test ( \test ) , .\result ( \result ) , .\tck ( \tck ) , .\select ( \select ) , .\a ( \a ) , .\rst_n ( \rst_n ) , .\shift ( \shift ) 
    ); 

    wire[100:0] __serializable__ =
        101'b00010111010111011110100110100110001001101010010010000001100110011111000101000110100100110100000001000;
    reg[100:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \a = 0 ;
        \b = 0 ;
        \select = 0 ;
        \clk = 0 ;
        \rst_n = 1 ;
        \sin = 0 ;
        \shift = 0 ;
        \tck = 0 ;
        \test = 0 ;

        #(`CLOCK_PERIOD*5);
        rst_n = ~rst_n;
        shift = 1;
        test = 1;
        for (i = 0; i < 101; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 101; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serializable__ === __serial__) begin
            $display("Success: expected %b got %b", __serializable__, __serial__);
            $display("SUCCESS_STRING");
        end else begin
            $display("Failed: expected %b got %b", __serializable__, __serial__);
        end
        $finish;
    end
endmodule
